metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - memory
    - diskio
    - network
    - process
    - filesystem
  processors:
    - add_host_metadata: ~
    - add_cloud_metadata: ~

setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat-*"
setup.template.overwrite: true
setup.template.enabled: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"

