services:
  kong:
    container_name: kong
    image: kong/kong-gateway:3.8.0.0
    user: root
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    environment:
      - KONG_DATABASE=off
#      - KONG_PG_HOST=20.10.1.1
#      - KONG_PG_USER=kong
#      - KONG_PG_PASSWORD=12345678
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    networks:
      default:
         ipv4_address: 20.10.1.9

networks:
  default:
    external: true
    name: develop_net
