services:
  pyapi:
    container_name: pyapi
    image: rafly28/api:1
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
#    ports:
#      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-size: "20m"
        max-file: "5"
    networks:
      default:
         ipv4_address: 20.10.1.2
  pyapi_2:
    container_name: pyapi_2
    image: rafly28/api:1
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
#    ports:
#      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-size: "20m"
        max-file: "5"
    networks:
      default:
         ipv4_address: 20.10.1.3
  pyapi_3:
    container_name: pyapi_3
    image: rafly28/api:1
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
#    ports:
#      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-size: "20m"
        max-file: "5"
    networks:
      default:
         ipv4_address: 20.10.1.4

networks:
  default:
    external: true
    name: develop_net
