services:
  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus:latest
    ports:
      - "x.x.x.x:9090:9090" #Forward to IP
    volumes:
      - prometheus_data:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=60d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-size: "20m"
        max-file: "5"
    networks:
      default:
        ipv4_address: x.x.x.x #IP Docker Network

volumes:
  prometheus_data:

networks:
  default:
    name: xxx #Docker Network Name
    external: true
